const PROPERTIES = [
    "All Properties",
    "1869 West",
    "214 Vine",
    "Aspen Court",
    "Aston Pointe",
    "Cheltenham Station", 
    "Cherry Hill Towers",
    "Chesapeake Pointe",
    "Chesterfield Flats",
    "Cosmopolitan",
    "Fox Pointe",
    "Franklin Commons",
    "Greenspring",
    "Harborstone",
    "Haven New Providence",
    "Holly Court",
    "Hunters Crossing",
    "Iron Ridge",
    "James River Pointe",
    "Joralemon",
    "Landmark at Glenmont Station",
    "Lehigh Square",
    "Liberty Pointe",
    "Mariner's Pointe",
    "Metal Works",
    "Metro Pointe",
    "Orchard Park",
    "Overlook",
    "Parc at Cherry Hill",
    "Parc at Lyndhurst",
    "Parc at Maplewood Station",
    "Parc at Roxbury",
    "Parc at Summit",
    "Parc at West Point",
    "Pointe at Northern Woods",
    "Pointe at River City",
    "Reserves at Arlington",
    "Reserves at Tidewater",
    "River Oaks",
    "River Pointe",
    "SilverLake",
    "Springhouse Townhomes",
    "Stonegate at Iron Ridge",
    "Terminal 21",
    "The Addison",
    "The Alden",
    "The Brunswick",
    "The Collection at Scotland Heights",
    "The Colony at Chews Landing",
    "The Commons",
    "The Flats at Columbia Pike",
    "The George New Brunswick",
    "The Meridian Apartments",
    "The Monroe",
    "The Nolan",
    "The Residences at St. Joseph Court",
    "The Ridge",
    "The View North Hills",
    "The Wellington",
    "The Woodlands",
    "Valley Park",
    "Westover Pointe",
    "Yorkshire Apartments"
   ];

   export default PROPERTIES;